### ISSUE TITLE
Types of objects it can compress

### ISSUE THREAD

**Issue by MAK11** [Cyan4973/zstd#10]
Hi,
is this an alternative to Gzip? 
Also, what kind of files/objects can it compress - just base HTML or also JS, CSS, Images etc? 
Lastly, can it be deployed to any OS - Apache/IIS?
Also, if I need to 'activate' this on an existing website, what steps do I need to follow?

**Comment by Cyan4973** [comment]
Hello

Keep in mind that this is a first release, it will require some tuning and testing to get all the intended properties.
That being said, there is no "limit" to the kind of files/objects that can be compressed, nor platform targeted. The algorithm is lossless and generic, like gzip. The code is supposed to be portable. Hopefully, a few wrapper will also help to make it available for a few more languages beyond C.

Note that zstd is still considered in "beta" phase, and will require some time and feedback to reach final "production" status.

Regards

**Comment by MAK11** [comment]
Thanks for the reply @Cyan4973
