### ISSUE TITLE
searchLength=7 aliases searchLength=4

### ISSUE THREAD

**Issue by benrg** [Cyan4973/zstd#101]
searchLength=7 in ZSTD_parameters is permitted, but it seems to give exactly the same compression and speed results as searchLength=4. Possibly this is because of the switches on matchLengthSearch in the code that have cases for 4-6 but not 7.

**Comment by Cyan4973** [comment]
Correct.

I omitted this combination in the source code, in order to reduce binary size, since this combination never happens, except for fast strategy.

**Comment by benrg** [comment]
I think that was true in 0.4.4, but 0.4.5 has searchLength=7 in combination with ZSTD_greedy and ZSTD_lazy in the <= 256 KB table.

**Comment by Cyan4973** [comment]
You are totally right.

This is mistake, and should be 4.
It went undetected as 7 is automatically translated into 4 ...

**Comment by Cyan4973** [comment]
`zstd_static.h` has been fixed
