### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by luben** [Cyan4973/zstd#102]
Hi,

I have tried to run some tests in parallel and noticed them failing non-deterministically: 

- ZSTD_decompressContinue fails sometimes when executed in parallel with ZSTD_compress
- ZSTD_compressContinue sometimes gives wrong results when executed in parallel with ZSTD_decompressContinue
- and the other way around: ZSTD_decompressContinue fails when executed in parallel with ZSTD_compressContinue.

When I say fails it is with "corruption_detected" error. When I say "non-deterministically" it means that consecutive run with the exact same inputs succeeds. I was suspecting my code is not thread safe so I  ran in parallel different classes that don't share any code except the libzstd binary (like the above cases) to rule out my own faults. One additional observation: decompressContinue fails only if the original size exceed some threshold, e.g. 1M for levels 1,3,6; 2M for level 9. The parallel Zstd_compress is running with random small bufferes (0-32k) when decompressContinue fails.

So some questions:

- is there anything that should be synchronized?
- I am still not sure if I am not doing something stupid so some advises where I should be careful are welcome.

Regards,
luben

**Comment by luben** [comment]
Hm, it could have be interplay of GC and locking issue. I have to test something.

**Comment by Cyan4973** [comment]
Hi @luben . 

zstd streaming interface is supposed to be thread safe.
It only uses information from local context, so as long as you have one context per thread, there is no race-condition to worry about.

**Comment by luben** [comment]
Yes, I looked over the code and there is no global state. I suspect that the JVM is not resprecing the buffer pinning and it shows under GC pressure only - it moves them while compression/decompression is in progress.  I have to test this and possibly allocate off-heap memory for the buffers or use the buffered version that you provide already.

**Comment by luben** [comment]
Yes, it is a problem with JVM not pinning the buffers, I have confirmed. I still have to find a proper solution. Closing it now as it is not a problem of the library.
