### ISSUE TITLE
use case: HTTP/2 HPACK ?

### ISSUE THREAD

**Issue by tomByrer** [Cyan4973/zstd#104]
The new HTTP compresses headers, with a static-expanding table:
talk: https://youtu.be/r5oT_2ndjms?list=PLNYkxOF6rcICcHeQY02XLvoGL34rZFWZn&t=820
spec: https://httpwg.github.io/specs/rfc7541.html
implementation: https://github.com/twitter/hpack/tree/master/hpack/src/main/java/com/twitter/hpack

Might make cookies make a comeback.

**Comment by Cyan4973** [comment]
@tomByrer , that would be a wonderful use case,
but I'm not sure to understand how it could be possible to get back into hpack at this stage.
hpack seems completely settled by now, and has selected security and simplicity as its core principles, for fairly good reasons considering it was an answer to CRIME attack vector. It also eliminated any possible expansion in the process (on purpose).

So maybe I just don't understand hpack well enough, or I don't see how it could make use of zstd.

**Comment by tomByrer** [comment]
You presented good points.  I'll keep in mind; hopefully I'll get time to
investigate further.
