### ISSUE TITLE
CUDA/OpenCL compressing/decompressing algorithm execution

### ISSUE THREAD

**Issue by mailagentrus** [Cyan4973/zstd#111]
Is it possible to "split" algorithm to many compressing/decompressing parallels blocks? It will be great idea to speedup library up to 10x.
CUDA is my hobby and I want to help improve zstd in future :)

**Comment by Cyan4973** [comment]
You're very welcomed Artyom.

There are limits to what can be done in parallel.

Basically, compressing / decompressing a block involves 2 parts : 
- Match Copy
- Entropy Coding

For the time being, entropy coding is completely independent within each block (_this could change in the future_). That means it's possible to encode / decode this stage within multiple blocks in parallel, store the result, and make it available to the next stage.

Unfortunately, Match Copy is not so kind. Especially during the decompression stage, decompressing a block requires access to previous blocks, which must therefore be already decoded. Serial in nature.

Going around this limitation would require independent blocks.
This is a valid use case btw : in many data structures, random access is important, so blocks are independent and tiny.

Small independent blocks hurt compression badly though. A mitigation solution is to use a shared dictionary, a kind of "static prefix" which is going to be used for all blocks. All block operations remain independent, and thus can be parallelized.

As one can guess, it's a pretty advanced topic. I believe a bit more work is required to get there.

In the meantime, if you are interested in challenging your CUDA skills, I can only invite you to try compressing / decompressing small independent blocks. It's going to be pretty difficult already, and will require you to get a good understanding of zstd internals.

**Comment by tomByrer** [comment]
When I was doing audio DSP programming, I found CUDA only helped in some scenarios, when processing savings was worth the data transfer costs.  Usually I found SSE optimizations easier & less friction.

**Comment by Cyan4973** [comment]
Should we keep this issue opened ?
Any new item in the foreseeable future ?

**Comment by mailagentrus** [comment]
Close this issue, please. It is impossible to integrate cuda support for the foreseeable future...

**Comment by coreleon** [comment]
> Is it possible to "split" algorithm to many compressing/decompressing parallels blocks? It will be great idea to speedup library up to 10x. CUDA is my hobby and I want to help improve zstd in future :)

Programming IS NOT A HOBBY ! It is a way o life ! Go get a life and find a real hobby !
Programming is a crucial process that has also be fatal to other people !
Get educated IF you want to be called a programmer !
