### ISSUE TITLE
zstd_legacy.h is missing - include attempted when ZSTD_LEGACY_SUPPORT is defined

### ISSUE THREAD

**Issue by TurtleSimos** [Cyan4973/zstd#113]
ZSTD_LEGACY_SUPPORT if not defined is defined to 1 in zstd_decompress.c

Then later in the file:

#if defined(ZSTD_LEGACY_SUPPORT) && (ZSTD_LEGACY_SUPPORT==1)
#  include "zstd_legacy.h"
#endif

However, zstd_legacy.h isn't present on github.

**Comment by Cyan4973** [comment]
It is present [in the `legacy` folder](https://github.com/Cyan4973/zstd/tree/master/lib/legacy)

The provided `Makefile` is supposed to automatically include this directory.

**Comment by TurtleSimos** [comment]
Ah, my mistake - I was updating ZStd in lzbench, which doesn't have the folder.

How about defaulting ZSTD_LEGACY_SUPPORT to 0, so that the legacy folder is only required if specifically desired?

**Comment by Cyan4973** [comment]
It's a matter of preference.
I'm not sure whichever option is better "by default".
So I opted for the "safer" one, so that people / projects having used Zstd prior version don't get accidentally blocked.

**Comment by TurtleSimos** [comment]
Sure, understood. I was assuming from the major version being zero, that api changes were assumed to be okay at any time. That is minor issue with semantic versioning before the first major release.
Thank you.

**Comment by Cyan4973** [comment]
Actually, thinking again about it, something I could do and *feels* logical : 
- when built using the default provided `Makefile` : set `ZSTD_LEGACY_SUPPORT` to 1
- when file is just being copy pasted into another project and no  `ZSTD_LEGACY_SUPPORT` is provided, set it to 0

This way, when including zstd into another project, the expectation, in general, is to not need additional legacy files.

**Comment by TurtleSimos** [comment]
That looks to be a very good solution to me. It is difficult to balance having the code out there for people to use and report bugs etc, before committing to a major version. Keeping the main lib folder as current and self sufficient would make adoption easy, while minimizing the penalty for early adoptors to migrate to changes.

**Comment by Cyan4973** [comment]
pushed into [dev branch](https://github.com/Cyan4973/zstd/tree/dev)
