### ISSUE TITLE
cannot decompress : Error "Destination buffer is too small"

### ISSUE THREAD

**Issue by astrotuna201** [Cyan4973/zstd#155]
Hi, 

thanks for the great work, much appreciated!
In the latest version I tested, there appears to be some error (commit b44be74 on alternate3).

I do not know if it occurs in earlier versions. 

I compress a file (either using the library, or with the cli), compression level -19
compression succeeds, and the correct frameContentSize of 505092 is written into the header.

However, decompression fails with error "Destination buffer is too small" ...

Attached a ZIP of the original and compressed files ...
[Archive.zip](https://github.com/Cyan4973/zstd/files/193320/Archive.zip)

**Comment by Cyan4973** [comment]
Thanks for notification @astrotuna201 !

`alternate3` is a development branch, not yet considered completely stable.

That being said, the intention is to make it stable, so when it feels ready, I will use your test case to verify it works properly, and fix the issue if it's still there.

regards

**Comment by Cyan4973** [comment]
Hi @astrotuna201 

I've been testing your file with latest development version, at `dev060`.

It seems this specific bug is no longer present, as `zstd` can successfully compress and decompress the file without error nor distortion.

It cannot however decode the compressed file you shipped, and detects a corruption. So I guess the compressed file was indeed corrupted by this older development version.

**Comment by Cyan4973** [comment]
Fixed in v0.6.0
