### ISSUE TITLE
"Error 32 : Read error" from FIO_decompressFrame in fileio.c on compressed empty string

### ISSUE THREAD

**Issue by thatsafunnyname** [Cyan4973/zstd#176]
Hello and thank you for zstd,

This reproducer:

    echo -n '' | zstd - --stdout | zstd -d --stdout
    "Error 32 : Read error"
 
produces the error from this commit onwards https://github.com/Cyan4973/zstd/tree/09b21ee2f67b4fd1dd2bfccb538d38f7811b8ad6 "fix fileio bug with new zbuff" (including the dev branch).
 
I am using default build tools and settings on RHEL6.6 on x86_64.  I see this at all compression levels, tested with:
 
    seq 1 22 | xargs -t -I {} bash -c "echo -n '' | programs/zstd -{} - --stdout | 
    programs/zstd -d --stdout ; echo \$?"

The commit and the one prior produce the same output:

    echo -n '' | zstd-09b21ee2f67b4fd1dd2bfccb538d38f7811b8ad6/programs/zstd - --stdout | base64
    JrUv/QfAAAA=
    echo -n '' | zstd-1c2c2bcaffb95a9516b907aec35c2ae7a8183b09/programs/zstd - --stdout | base64
    JrUv/QfAAAA=
 
When testing using a file (from the default level 1 compression) I see the same error:
 
    base64 test.zstd
    JrUv/QfAAAA=
 
    zstd-09b21ee2f67b4fd1dd2bfccb538d38f7811b8ad6/programs/zstd -d test.zstd --stdout ; echo $?
    Error 32 : Read error
    32
    zstd-1c2c2bcaffb95a9516b907aec35c2ae7a8183b09/programs/zstd -d test.zstd --stdout ; echo $?
    0
 
With a breakpoint on `FIO_decompressFrame` in `fileio.c` , `alreadyLoaded=4` , `ZSTD_frameHeaderSize_max=13` so `toLoad=9` fread returns 4 and this is assigned to `checkSize`, but `4!=9` so we get the `EXM_THROW(32, "Read error")`.
 
     /* Complete Header loading */
     {   size_t const toLoad = ZSTD_frameHeaderSize_max - alreadyLoaded;   
                     /* assumption : alreadyLoaded <= ZSTD_frameHeaderSize_max */
         size_t const checkSize = fread(((char*)ress.srcBuffer) + alreadyLoaded, 1, toLoad, finput);
         if (checkSize != toLoad) EXM_THROW(32, "Read error");
     }
     readSize = ZSTD_frameHeaderSize_max;

Thank you in advance for taking a look.

**Comment by thatsafunnyname** [comment]
For what is is worth, checking if the `checkSize` is less than a `toLoad_min` calculated from `ZSTD_frameHeaderSize_min - alreadyLoaded`
before throwing passes all "make test" tests on commit 09b21ee2f67b4fd1dd2bfccb538d38f7811b8ad6.

    /* Complete Header loading */
    {   size_t const toLoad = ZSTD_frameHeaderSize_max - alreadyLoaded;   /* assumption : alreadyLoaded <= ZSTD_frameHeaderSize_max */
        size_t const checkSize = fread(((char*)ress.srcBuffer) + alreadyLoaded, 1, toLoad, finput);
        if (checkSize !=toLoad) {
          size_t const toLoad_min = ZSTD_frameHeaderSize_min - alreadyLoaded;
          if ( checkSize < toLoad_min ){
            EXM_THROW(32, "Read error");
          }
        }
    }

**Comment by Cyan4973** [comment]
Thanks for the very clear report @thatsafunnyname .
I believe it gives some very good hints on what the problem is and how to fix it.

**Comment by Cyan4973** [comment]
Latest update of "dev" branch should fix this issue.
The relevant test case has been added to zstd standard test suite. Thanks @thatsafunnyname !

**Comment by thatsafunnyname** [comment]
Thank you.
