### ISSUE TITLE
Training a large dataset spends more time updating the Windows command prompt than reading the actual data.

### ISSUE THREAD

**Issue by KrzysFR** [Cyan4973/zstd#177]
I was training a dictionary on set of about 20.000 files in a folder (~2.5 GB), and noticed that zstd was spending a long time just updating the console with `loading {FILENAME} ...` for each and every file, instead of doing actual work.

Both runs done with a empty disk cache (where the overhead of the console write will be visible)

A: `zstd.exe --train uncompressed/* -o test.dict`
B: `zstd.exe --train uncompressed/* -o test.dict 2> output.log`
_The command B redirects stderr to a text file, so all `loading XYZ...` don't have to update the UI_

CPU profile (A left, B right)
![image](https://cloud.githubusercontent.com/assets/1662235/14856243/a47d7686-0c97-11e6-9955-2fd7cf45e977.png)
The horizontal arrow represent the time when I see the `loading FILE....` happening.

Looking at the disk IO (A left, B, right)
![image](https://cloud.githubusercontent.com/assets/1662235/14856263/b2d61f26-0c97-11e6-94e4-4d42b1d60af3.png)

Due to the throttling caused by the console, I'm reading only at 70 MB/sec. When the console is redirected to a file, I seed a burst at 1.0+ GB/sec (I have a Samsung SM951 M.2)

I know by experience that the Windows command prompt is very very slow when writing a lot of stuff to the console in an inner loop, and that test of batch jobs that have to write a lot of text will sometime execute 10x or 100x faster when you remove the log altogether, or when you only output a log for every 10 or 100 items.

**Comment by Cyan4973** [comment]
This is a very good point.
Display load should be tamed.
I'll look into it.

**Comment by Cyan4973** [comment]
Latest update of "dev" branch should fix this issue.
The traditional method for such case is to use `DISPLAYUPDATE()` macro, which only prints to console if a minimum delay between 2 consecutive prints has been reached.
Should highly reduce print load under described scenario.

**Comment by KrzysFR** [comment]
Thanks, can't really test at the moment because I'm on a flaky train station wifi connection. Will try to test it later tonight if possible.

**Comment by Cyan4973** [comment]
Fixed in v0.6.1
