### ISSUE TITLE
vs gzip & Zophli?

### ISSUE THREAD

**Issue by tomByrer** [Cyan4973/zstd#2]
I'm curious if this is `compress` web-compatible please?

**Comment by Cyan4973** [comment]
Hi Tom
I'm not sure to understand your question.
Could you elaborate please ?

**Comment by kitt3n** [comment]
Allows web servers to dynamically compress content users are asking for, making the packets smaller :)

**Comment by Cyan4973** [comment]
Yes, the plan is for Zstd to be useful to such application.

That being said, this particular first-day API is still a bit limited.
It will need to mature a bit to live up to this promise.

Fortunately, LZ4 experience will help a lot to reach this point.
