### ISSUE TITLE
ZSTD_compressBlock() results vary "randomly" in size and performance

### ISSUE THREAD

**Issue by KrzysFR** [Cyan4973/zstd#215]
I'm having some weird results with `ZSTD_compressBlock` which, for the same input and same compression level, alternates between "fast by compress less" and "extremely slow by compress more"

The setup: input text is the lyrics of a song (3,138 bytes, single repetition).
The test: compress the lyrics using a single call to `ZSTD_compressBlock`, using a dedicated compression context each time.

I repeat the test about a 100 times each, and see the result alternating between two states:
- "fast": where it compress in about 40 µs, into 1,818 bytes (ratio 1,72)
- "slow": where it compress ion ~200 _milliseconds_, into 1,6384 bytes (ratio 1,92)
- for comparison, a call to `ZSTD_compress()` produce a result of 1,721 bytes (ratio 1.82).

The "slow" case seems to produce the correct output (a little bit smaller than `ZSTD_compress()` which would be expected without all the framing. But it is VERY slow.

The "fast" case produce an output that is a lot larger than `ZSTD_compress()`, but in the same wall clock time.

The code in .NET looks like this:
```CSharp
public static bool TryCompressBlock(ArraySegment<byte> input, int compressionLevel, ref byte[] buffer, out ArraySegment<byte> compressed)
{
	Contract.NotNull(input.Array, nameof(input));

	// ensure output buffer is correctly sized for this input
	int minCapacity = (int) NativeLib.CompressBound(input.Count);
	if (buffer == null || buffer.Length < minCapacity)
	{ // previous buffer too small, replace with larger one
		buffer = new byte[minCapacity]; //TODO: buffer pool, rounding to power of two !
	}

	unsafe
	{
		fixed (byte* src = &input.Array[input.Offset])
		fixed (byte* dst = &buffer[0])
		{
			IntPtr cctx = default(IntPtr);
			try
			{
				NativeLib.CreateCompressionContext(out cctx);
				byte* ptr = dst;
				uint capa = (uint) buffer.Length;
				uint n = NativeLib.CompressBegin(cctx, ptr, capa, compressionLevel);
				n += NativeLib.CompressBlock(cctx, ptr + n, checked(capa - n), src, (uint) input.Count);
				compressed = new ArraySegment<byte>(buffer, 0, checked((int) n));
				return true;
			}
			finally
			{
				NativeLib.FreeCompressionContext(ref cctx);
			}
		}
	}
}
```
_The `NativeLib` class contains thin wrappers to the `zstdlib.dll` and only handle checking for error codes and throwing .NET exceptions._

Now, one thing that I have noticed, that MAY or MAY NOT be related at all, but when the slow down happens, I see that my Visual Studio process is using a lot of CPU (but not all cores) due to some extensions kicking in code analysis. When this happens `ZSTD_compressBlock()` is slow but more efficient. And when the cpu goes down, then `ZSTD_compressBlock()` returns almost immediately to the "fast" state 

Here is an example of a run:
```
- Plaint Text   size: 3,138 bytes
- ZSTD_compress(3,138) => 1,721 bytes
Test started:
- ZSTD_compressBlock(3,138) => 1,818 bytes in 1.212 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.078 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.047 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.042 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.040 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.046 ms
//... for a while...
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.039 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.037 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.037 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.046 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.039 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.045 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.037 ms
// suddenly switch to "slow"
- ZSTD_compressBlock(3,138) => 1,634 bytes in 209.484 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 193.060 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 198.562 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 220.046 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 209.110 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 200.615 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 250.310 ms
// ....for a while...
- ZSTD_compressBlock(3,138) => 1,634 bytes in 206.018 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 211.330 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 204.598 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 205.166 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 205.574 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 204.261 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 205.774 ms
- ZSTD_compressBlock(3,138) => 1,634 bytes in 199.544 ms
// now switch back to "fast"
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.081 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.044 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.045 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.044 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.041 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.053 ms
- ZSTD_compressBlock(3,138) => 1,818 bytes in 0.041 ms

```

  Or just maybe i'm being trolled by a [red fish changing side in a fishtank](https://youtu.be/IDi2NlsA4nI?t=4m57s)?
  ![image](https://cloud.githubusercontent.com/assets/1662235/16160381/1199659c-34c8-11e6-964d-889abbee3238.png)

Is this method sensitive to cpu performance? to the point where the compressed result would change?

**Comment by Cyan4973** [comment]
That's indeed very strange.
`ZSTD_compressBlock()` shouldn't give different results when called repetitively.

The only idea that comes to mind is that maybe the compression level provided is different.
Perhaps an initialization issue, triggered by the extension ?

If `ZSTD_compressBegin()` is invoked with a high compression level, it will allocate a lot of memory. That could easily explain the very large delay to compress a single block.

**Comment by KrzysFR** [comment]
The test is basically a `for(int i=0; i < 100; i++) { run_test(); }`, so the compression level should always be 1, as well as the rest of the parameters.

I'll try to run some profiling, but the code that initializes contexts, and as well as call `ZSTD_compressBegin()` / `ZSTD_compressEnd()` is shared with the rest of the implementation, so I'm almost certain it works.

I will also try to find what compression level would give me the same size and equivalent run time.

**Comment by KrzysFR** [comment]
So, running a profiler gives an interesting result: under the profiler I was not able to observe the "fast" result. And the "slow" result gives this:
![image](https://cloud.githubusercontent.com/assets/1662235/16171951/db2e8bbc-357c-11e6-8542-54a457098909.png)

_each 'Invoke' call is the actual marshalled call to zstdlib.dll from .NET, the method above it is the managed wrapper._

It looks like both `ZSTD_compressBegin` and `ZSTD_freeCCtx` takes most of the time (74% and 25.7%) with the rest (including `ZSTD_compressBlock` itself) taking less than 0.3%...

The average call time of `ZSTD_compressBeing` is 150ms and `ZSTD_freeCCtx` is 52ms here.

Even at level 22, `ZSTD_compress` yields 1,647 bytes in well under 0.5 milliseconds.

**Comment by KrzysFR** [comment]
Never mind... I was indeed being trolled by the .NET marshaling stack protection hiding an error in the definition of `ZSTD_compressBegin`, that I forgot to update after an API change at some point.

My version of `ZSTD_compressBegin` still had the `dst` and `dstSize` arguments, with `compressionLevel` last.

Amazingly, the call did not crash, except that the 32 upper bits if my 64-bit memory pointer were passed as the value for `compressionLevel`... which most of the times was probably 0, but sometimes not (randomly, under a profiler...). I wish it would have blown up with a "stack corrupted" exception, instead of trying to fix the stack imbalance under the cover...

Everything works fine now, but I'll have to go back to each API wrapper and check if they are synched with 0.7.0.

**Comment by KrzysFR** [comment]
Looking back on this issue, I'm wondering if `ZSTD_getCParams` should return an error, when the `compressionLevel` is outside the legal range, instead of silently clipping the values to either `ZSTD_DEFAULT_CLEVEL` or `ZSTD_MAX_CLEVEL`. 

This is not the first time I had the same issue with .NET method declaration not matching the one in the `.h` (mistake due to copy/pasta, or API changed in new version), and `ZSTD_getCParams` could have helped detect the issue sooner. Right now, with garbage input, it will either clamp to 1 or 22, and produce the pattern of calls being either 'super fast' or 'super slow', which can be confusing for the developer.

**Comment by Cyan4973** [comment]
Good point.

It does introduce 2 difficulties though : 

- `ZSTD_getCParams()` return type does not allow sending an error. This prototype would need to change to make this possible.
- There's also a question of how it should behave with existing codes when level definitions change : 
suppose the range of values get reduced, what should be the behavior for an existing program using a now-invalid clevel, and linked to an updated libzstd dll ? should it error out ? or just continue with max possible ?

**Comment by KrzysFR** [comment]
> ZSTD_getCParams() return type does not allow sending an error. This prototype would need to change to make this possible.

Maybe it should have a `ZSTD_compressionParameters* paramPtr` argument? There are API where you can discover the required size by first calling with NULL, get the size somewhere, and then call again. If the size is a constant, I prefer a dedicated method that returns it directly.

> what should be the behavior for an existing program using a now-invalid clevel

If only new compression levels (say 23 to 30) are added in the future, I guess programs using the current range (1..22) would not have any issue. Also, there is `ZSTD_maxCLevel()` that I use to discover the max compression level and do a range check at runtime.

Also, if someone uses `9999` as a placeholder value for "as high as possible", this is a bit dangerous already: If in v2.x you add compression level `99` which can take up to a few minutes to compress, this will be a sort of breaking change for the calling app (where level 22 would take a hundred ms or a few seconds).

**Comment by Cyan4973** [comment]
> If only new compression levels (say 23 to 30) are added in the future, I guess programs using the current range (1..22) would not have any issue.

Yes sure.
The only issue happens if the range of values _shrinks_ . That's a possibility I do not rule out completely right now, since some people believe it should be reduced.
Though no decision in this direction yet.

> Maybe it should have a ZSTD_compressionParameters* paramPtr argument?

Yes, that's the easiest way.
It makes usage slightly more complex, but well...
