### ISSUE TITLE
Functions to calculate approximate memory usage needed for compression and decompression based on compression_level

### ISSUE THREAD

**Issue by GregSlazinski** [Cyan4973/zstd#225]
Is it possible to provide such functions?
Such as :
int64 ZSTD_CompressionMemUsage(int compression_level);
int64 ZSTD_DecompressionMemUsage(int compression_level);

In my program, I use multi-threaded compression, by executing multiple compressors on multiple threads.
However I limit the number of simultaneous threads by the number of available memory .

For example if system has 4 GB of RAM.
And each call to compress function would require 1 GB of memory usage.
Based on that info I would know that I can create up to 4 threads.

However I was unable to find any information about memory usage for compressing and decompressing with ZSTD.

Thank you

**Comment by Cyan4973** [comment]
Yes, that's a good request.

I will think about introducing it in a future version.

In the meantime,
there are 2 "hidden functions" which may help you :

```
size_t ZSTD_sizeofCCtx(ZSTD_compressionParameters cParams);
// and
size_t ZSTD_sizeofDCtx (void);
```

They will provide what you ask for.
They are not public (yet). Their prototype are not guaranteed to remain stable in future versions, so see this as a stop-gap solution.

`ZSTD_compressionParameters cParams` is a set of parameters which controls the compression compress, and as a consequence controls its memory usage.

To get a set of parameters from a compression level, you can use : 
`ZSTD_compressionParameters ZSTD_getCParams(int compressionLevel, U64 srcSize, size_t dictSize);`
which is part of "experimental" API (requires to define `ZSTD_STATIC_LINKING_ONLY`).

**Comment by GregSlazinski** [comment]
Thanks,

I will use it in the mean-time.

Would be cool to have "ZSTD_sizeofCCtx" work without doing the allocations.

Thanks again

Greg

**Comment by Cyan4973** [comment]
Thinking again about it :
`ZSTD_sizeofCCtx()` could be interpreted as : 
- size of current `CCtx()` provided as argument
- size of a future `CCtx()` that will be created depending on a set of arguments

While the current prototype answers the second question,
on second look, given its name, it seems more logical for it to answer the first question.

For such a change, the new prototype would become : 
`size_t ZSTD_sizeofCCtx(const ZSTD_CCtx* cctx);`
and its implementation would be greatly simplified (just read already allocated space, which is already tracked internally).

But it would no longer answer the second question :
what will be the size of a _hypothetical future_ `ZSTD_CCtx` given a set of arguments ?

This second question is the one `paramgrill` needs.
According to your question, it's also the one you were looking for.

Therefore, a new prototype would become necessary to answer the 2nd question.
Which starts by selecting a new name expressive enough...

**Comment by GregSlazinski** [comment]
Hi,

Yes, I'd need the memory usage to be known without creating any contexts yet, to know how many contexts I can create in the future.

**Comment by Cyan4973** [comment]
I'm considering the following API : 

`ZSTD_sizeofCCtx()` would be changed to become the size of the current CCtx provided in argument : 
```
size_t ZSTD_sizeofCCtx(const ZSTD_CCtx* cctx);
```

A new prototype would be created : 
```
size_t ZSTD_estimateCCtxSize(ZSTD_compressionParameters cParams);
```

This one would answer the question : "what's going to be the size of a new CCtx if I create it with the following parameters ".

**Comment by GregSlazinski** [comment]
Hi, 

Yes, that would be great. 
Thanks

**Comment by Cyan4973** [comment]
In latest update of the "dev" branch,
there is a new function named `ZSTD_estimateCCtxSize()`
within the experimental section.

In contrast with earlier `ZSTD_sizeofCCtx()`, it doesn't allocate anything to provide a result.

For your testing

**Comment by GregSlazinski** [comment]
Many thanks! :>

**Comment by GregSlazinski** [comment]
One last suggestion is to include the size_t ZSTD_sizeofDCtx(void); into the zstd.h header file
So I don't need to do:
```
   #include "../../../ThirdPartyLibs/Zstd/lib/common/zstd.h"
   extern "C" size_t ZSTD_sizeofDCtx(void);

```

**Comment by Cyan4973** [comment]
Sure !
added

**Comment by GregSlazinski** [comment]
Hi, 

I see that you've changed the ZSTD_sizeofDCtx to take as input an existing context. 
However I'd still need to know the approximate memory usage without creating any contexts. 
Thank you

**Comment by Cyan4973** [comment]
Well, this is to be more  "coherent" with `ZSTD_sizeofCCtx()`,
and in anticipation of potential changes in the futures.

But for the time being, `ZSTD_sizeofDCtx()` will always answer the same value,
because it's a POD type structure.

**Comment by GregSlazinski** [comment]
In that case, could you add ZSTD_estimateDCtxSize function?

**Comment by Cyan4973** [comment]
added in "dev" branch
