### ISSUE TITLE
Zstd 0.7.1 does not compile with VC2013 and VC2015

### ISSUE THREAD

**Issue by mcmilk** [Cyan4973/zstd#226]
This line is not understood by the compiler of Microsoft:
`static ZSTD_customMem const defaultCustomMem = { ZSTD_defaultAllocFunction, ZSTD_defaultFreeFunction, NULL };`

Here is the error message in german of it:
`cl   -DEXTERNAL_CODECS -D_7ZIP_LARGE_PAGES -DUNICODE -D_UNICODE -Gr -nologo -c -FoAMD64/ -W4 -WX -EHsc -Gy -GR- -GF -MT /Ox /Ot ../../Compress\ZstdDecoder.cpp ../../Compress\ZstdEncoder.cpp ../../Compress\ZstdRegister.cpp`

`z:\setups\7zip\dl-zstd\src\7z1602_zstd_070\c\zstd\zstd_internal.h(236) : error C2143: Syntaxfehler: Es fehlt ';' vor 'const'`

`z:\setups\7zip\dl-zstd\src\7z1602_zstd_070\c\zstd\zstd_internal.h(236) : error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht unterstützt.`

`z:\setups\7zip\dl-zstd\src\7z1602_zstd_070\c\zstd\zstd_internal.h(236) : error C2440: 'Initialisierung': 'initializer-list' kann nicht in 'const int' konvertiert werden`

`Es können lediglich Initialisierungslisten mit höchstens einem Element in diesen Typ konvertiert werden`

I haven't tried to get it fixed currently... I just wanted to add a note about it.

Best regards, Tino

**Comment by Cyan4973** [comment]
Thanks for notification @mcmilk !

This is very surprising : VC2013 and VC2015 and part of our regular automated tests, and work pretty well so far. See for example :
https://ci.appveyor.com/project/YannCollet/zstd/build/job/c671e680xybr6615

I also happen to have Visual Studio 2015 installed on my laptop, and it also compiles fine, without a single warning (with warning level 4).

Maybe there are some specific compilation conditions which can trigger this error ?

**Comment by mcmilk** [comment]
I am using this batch file: https://github.com/mcmilk/7-Zip-Zstd/blob/master/CPP/build-x64.cmd

This is the build log: https://github.com/mcmilk/7-Zip-Zstd/blob/master/CPP/build.txt

**Comment by Cyan4973** [comment]
According to your logs, all problems are concentrated on a single line : `zstd_internal.h(236)`,
which is :

```
static ZSTD_customMem const defaultCustomMem = { ZSTD_defaultAllocFunction, ZSTD_defaultFreeFunction, NULL };
```

Looking into detailed error log : 
`error C2143: Syntaxfehler: Es fehlt ";" vor "const"`
translating : 
`Syntax error: missing ' ; ' before " const "`

which is quite strange. 
The only way I'm able to produce this error is by removing the semicolon at the end of previous line 235.

Let's try a minor change in case it would help :
```
static const ZSTD_customMem defaultCustomMem = { ZSTD_defaultAllocFunction, ZSTD_defaultFreeFunction, NULL };
```

Maybe it will work better ...
(Note : this I'm unable to trigger the same problem, I can't tell if above proposal will work or not)


##### Side note : 

`error C4430: Fehlender Typspezifizierer - int wird angenommen. Hinweis: "default-int" wird von C++ nicht untersttzt.`
translating :
`Missing type specifier - int assumed . Note : " default- int " is not supported by C ++ .`

which seems to imply that the code is compiled in c++ mode ?

Note that I've also tried to compiler zstd using c++ convention on both VS2013 and VS2015,
in both cases, it worked, without error ... :question:

**Comment by mcmilk** [comment]
> which seems to imply that the code is compiled in c++ mode ?
Yes, good point, thats the reason.
The Code is C++ and includes zbuff_static.h ... which itself includes zstd_internal.h for the definition of MIN() ... this internal header needs to be seen in C Mode... thats the error I think.

Moving the MIN/MAX declaration to zstd_static.h and than removing zstd_inernal.h from zbuff_static.h fixed the compilation issue. I could made a patch for it, if needed...

Have a nice football sunday ;)

**Comment by Cyan4973** [comment]
> The Code is C++ and includes zbuff_static.h 

Note that `zbuff_static.h` [doesn't exist anymore](https://github.com/Cyan4973/zstd/tree/master/lib/common).
(for the record, neither `zstd_static.h` nor `zdict_static.h`).
It could be a relic of previous version in your directory.

If you need access to its advanced definition, such as `ZBUFF_compressInit_advanced()`,
the new methodology is to
`#define ZBUFF_STATIC_LINKING_ONLY` before `#include "zbuff.h"`.
See : https://github.com/Cyan4973/zstd/blob/master/lib/common/zbuff.h#L163

It also has no longer any dependency on `zstd_internal.h`.

**Comment by mcmilk** [comment]
Okay, I will change that in the next release of 7-Zip Zstd, thanks for the help.
