### ISSUE TITLE
Minor: Benchmark: worse ratio with blocksize (-B) larger than the entire file

### ISSUE THREAD

**Issue by Bloody2** [Cyan4973/zstd#228]
Howdy,

I've noticed that benchmarking a 16K file with -B500000 (for example), the compression ratio suffers:

$ zstd -b text_00016k
 1#text_00016k       :     16384 ->      6661 (2.460), 190.8 MB/s , 471.5 MB/s 

$ zstd -b -B500000 text_00016k
using blocks of size 488 KB 
 1#text_00016k       :     16384 ->      6854 (2.390), 204.4 MB/s , 626.0 MB/s 

Is this intentional or perhaps a minor bug?

It's me btw., Oliver Lange. I promised to switch to github instead of writing emails.. ;)

**Comment by Cyan4973** [comment]
Which version of zstd are you using in this test ?

**Comment by Bloody2** [comment]
I thought is was 0.6.1 but the header says 0.6.0... i'll test this with the new release tomorrow or the day after tomorrow and report back to you.

**Comment by Bloody2** [comment]
Update: (closed with v0.7.1)

I could not reproduce the issue with v0.7.1 (testing 3 files and 5 block sizes).

I see that BMK_benchMem() now uses ZSTD_createCDict() instead of v0.6.1 using
ZSTD_compressBegin_advanced() with it's pledgedSrcSize parameter which is now
entirely out of the equasion.

That should explain why v0.7.1 now works consistently.

Sorry for making the noise...

**Comment by Cyan4973** [comment]
You guessed it right : 
the "issue" comes from `pledgedSrcSize`, which is used to dynamically adapt compression parameters.

In previous versions, settings `-B` parameter would have the effect of setting this value too.
This is no longer the case.

Note that I will re-introduce `pledgedSrcSize` from `ZSTD_createCDict_advanced()` in future version. But its value will no longer depend on `-B` parameter.
