### ISSUE TITLE
Possible leak in ZDICT_trainFromBuffer_unsafe

### ISSUE THREAD

**Issue by nemequ** [Cyan4973/zstd#229]
I'm playing around with scan-build, and it picked this up: if the check on [line 926](https://github.com/Cyan4973/zstd/blob/23042929daf5fb207bfadaffdd85325bfbd16e24/lib/dictBuilder/zdict.c#L926) fails, the memory allocated on [line 919](https://github.com/Cyan4973/zstd/blob/23042929daf5fb207bfadaffdd85325bfbd16e24/lib/dictBuilder/zdict.c#L919) will be lost.

**Comment by Cyan4973** [comment]
Good point ! Thanks for notification !

**Comment by Cyan4973** [comment]
Should be fixed in latest "dev" branch update

**Comment by Cyan4973** [comment]
fixed in v0.7.2
