### ISSUE TITLE
zstd CLI should support GNU "--" separator for file list

### ISSUE THREAD

**Issue by chipturner** [Cyan4973/zstd#230]
gzip and other standard linux/GNU tools let you specify a parameter, "--", after which all parameters are file names and "-" interpretation is no longer performed.  This allows for manipulation of files that start with a "-" which is both convenient and a security feature.

**Comment by Cyan4973** [comment]
Latest update in "dev" branch is now providing this functionality.

**Comment by Cyan4973** [comment]
merged into v0.7.3
