### ISSUE TITLE
Memory leak in ZDICT_trainFromBuffer_unsafe

### ISSUE THREAD

**Issue by velavokr** [Cyan4973/zstd#233]
The function simply exits on errors without freeing the buffer it allocated
https://github.com/Cyan4973/zstd/blob/master/lib/dictBuilder/zdict.c#L926

**Comment by Cyan4973** [comment]
Thanks for notification @velavokr .

Indeed, you are right,
this is #229 , currently fixed in "dev" branch

**Comment by velavokr** [comment]
Didn't read other issues before posting mine, sorry.

Do you mind an offtopic question regarding the fresh 0.7.1? 

Are 0.6.1 and 0.7.1 compatible when encoding with 0.7.1 and decoding with 0.6.1? 

Because I am very happy to see 0.7.1 release and really want to migrate on it but not sure what migration strategy to pick. If they are fully compatible then it's ok to just replace. If not, it will take us a bit more effort, zstd is a huge success here in Yandex.

Thanks in advance!

**Comment by Cyan4973** [comment]
Sure !

v0.7.1 is backward compatible with v0.6.1 : it can read data produced by v0.6.1,
as long as "legacy mode" is enabled, which is by default the case for both library and binary.

However, v0.6.1 cannot read data produced by v0.7.1.

**Comment by velavokr** [comment]
Thank you!
