### ISSUE TITLE
Separate define for 32/64 ZSTD_WINDOWLOG_MAX

### ISSUE THREAD

**Issue by GregSlazinski** [Cyan4973/zstd#239]
Is it possible to replace the following:
#define ZSTD_WINDOWLOG_MAX    ((U32)(MEM_32bits() ? 25 : 27))
to:
#define ZSTD_WINDOWLOG_MAX_32 25
#define ZSTD_WINDOWLOG_MAX_64 27
#define ZSTD_WINDOWLOG_MAX    ((U32)(MEM_32bits() ? ZSTD_WINDOWLOG_MAX_32 : ZSTD_WINDOWLOG_MAX_64))

I'm targetting both 32/64 platforms, and I want to know the minimum supported value by both platforms, in my case I will always use ZSTD_WINDOWLOG_MAX_32

LZHAM library does the same approach.

Thanks to this I don't need to store the WindowLog size in the compressed stream, but I can always calculate it based on decompressed size (which I already know).

**Comment by Cyan4973** [comment]
Yes

**Comment by Cyan4973** [comment]
Merged into v0.7.3
