### ISSUE TITLE
ZSTD_nextSrcSizeToDecompress()

### ISSUE THREAD

**Issue by doublex** [Cyan4973/zstd#243]
Dear Yann,

It would be great to know, if "ZSTD_nextSrcSizeToDecompress()" could result in a decompression or not.
E.g.: If I will read the 3-byte epilogue-header, "ZSTD_decompressContinue()" will not need a 128k output buffer.

Thanks!
Marcus

**Comment by Cyan4973** [comment]
The rule is as follows : 
after decoding the frame header
`ZSTD_nextSrcSizeToDecompress()` will alternate between : 
- decoding a block header (always 3 bytes)
- decoding a block content (any nb of bytes, though generally > 3 bytes)

When reading a block header, `ZSTD_decompressContinue()` will not produce any output.
Note that _epilogue_ counts as _block header_ in this scheme.

If you can track this alternate between _header_ and _content_, then you know when you'll need to provide a buffer or not.

**Comment by doublex** [comment]
You are really an excellent developer (I am porting LZ4 to ZSTD).
ZSTD is definitely great code.
Thanks for your hard work.
