### ISSUE TITLE
Example: Many Consecutive Small Data Compressions/Decompressions Of Unknown Size

### ISSUE THREAD

**Issue by kklouzal** [Cyan4973/zstd#244]
I'm migrating from LZ4 to ZStd and have the following use constraints:

I'm compressing many small blocks of variable size data limited to a maximum size.
The original, uncompressed, size of these blocks is unknown on the decompression side.
Again the maximum size of any uncompressed block will never exceed a specific value.

Compression and decompression will be handled by a single object which makes the use of dictionaries very appealing as this object can tune it's dictionary after each successive compression/decompression.

I know it's asking for a lot, but can anyone provide a most basic example that I can use to extrapolate the necessary procedure for compressing and decompressing data with the above outlined constraints?

This also raises a side question; Can the dictionary on the compression side be different from that of the decompression side? If we are transmitting our compressed data via any method this would allow dictionaries to tune themselves on each end?
For example in a client-server or peer-2-peer networking model where packets of data are sent to multiple recipients. Each recipient would have their own dictionary that could be updated and tuned with each successive compression/decompression of a packet.

**Comment by Cyan4973** [comment]
Welcome @kklouzal .

If you already used `LZ4_compressContinue()` in your previous code,
you will find `ZSTD_compressContinue()` to be quite familiar.
It's almost the same, with an added benefit : no need to save the size of each block,
it's already embedded in the compression format.

**Comment by Cyan4973** [comment]
In the "dev" branch, you'll find an [example directory](https://github.com/Cyan4973/zstd/tree/dev/examples), containing several example programs using zstd library.

The list of example is not complete yet, but the objective is to provide enough examples for everyone to feel at ease with zstd API (at least the "stable" part).

**Comment by Cyan4973** [comment]
Not sure what more can be done.
Please re-open the issue if you have specific questions
