### ISSUE TITLE
Incorrect format string specifier

### ISSUE THREAD

**Issue by nemequ** [Cyan4973/zstd#245]
`MINMATCHLENGTH` is a signed integer, you should use `%d` not `%u`.

```diff
diff --git a/lib/dictBuilder/zdict.c b/lib/dictBuilder/zdict.c
index f1af419..3e8bca2 100644
--- a/lib/dictBuilder/zdict.c
+++ b/lib/dictBuilder/zdict.c
@@ -284,7 +284,7 @@ static dictItem ZDICT_analyzePos(
         U32 refinedEnd = end;
 
         DISPLAYLEVEL(4, "\n");
-        DISPLAYLEVEL(4, "found %3u matches of length >= %u at pos %7u  ", (U32)(end-start), MINMATCHLENGTH, (U32)pos);
+        DISPLAYLEVEL(4, "found %3u matches of length >= %d at pos %7u  ", (U32)(end-start), MINMATCHLENGTH, (U32)pos);
         DISPLAYLEVEL(4, "\n");
 
         for (searchLength = MINMATCHLENGTH ; ; searchLength++) {
```

**Comment by Cyan4973** [comment]
I'm a bit surprised. I would have definitely agreed if :
`signed int MINMATCHLENGTH  = 7;`

But that's not the case, here : 
`#define MINMATCHLENGTH 7`

In this situation, I expect `7` to be automatically converted to the best fitting type, whether signed or unsigned, and even short or long.

**Comment by nemequ** [comment]
Nope, you could add a `U` (or `u`) suffix if you want the type to be unsigned, but according to [C99](http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf) § 6.4.4.1 by default "The type of an integer constant is the first of the corresponding list in which its value can be represented.", and the corresponding list is

 * int
 * long int
 * long long int

C likes to default to int for everything.

**Comment by Cyan4973** [comment]
Interestingly, it never caused any issue so far.

For example, in a loop, if I do something like : 
```
#define LIMIT 10
unsigned u;
const int iLimit = LIMIT ;
for (u=0; u< iLimit; u++)
```

compiler will complain about `u` and `iLimit` having different sign for the comparison.
But : 
```
#define LIMIT 10
unsigned u;
for (u=0; u < LIMIT ; u++)
```
doesn't cause any trouble, even though LIMIT is supposed to be an `int`.

**Comment by nemequ** [comment]
Good point, that is interesting :)

My guess is that the compiler uses some heuristics to make that warning less noisy; they wouldn't want to break `for(u=0 ; u < 10 ; u++)`.  Comparing values which differ in signedness is well-defined, it's just the source of enough bugs that a warning like that can be helpful, but warning about using an integer constant there would be too much.

**Comment by Cyan4973** [comment]
modified in dev branch
