### ISSUE TITLE
Doesn't compile with GCC 4.4

### ISSUE THREAD

**Issue by Cyan4973** [Cyan4973/zstd#25]
Error due to type redefinition.
Original discussion : #24 

Note : it's not an issue for later versions of GCC and clang, because the type redefinition defines exactly the same type. But earlier GCC versions nonetheless consider it an error.

**Comment by Cyan4973** [comment]
A fix is proposed within streamAPI2 branch : 
https://github.com/Cyan4973/zstd/tree/streamAPI2

**Comment by technion** [comment]
I can confirm the proposed branch resolves the issue.

**Comment by Cyan4973** [comment]
Thanks for testing

The streamAPI2 feature branch has been merged into dev.
https://github.com/Cyan4973/zstd/tree/dev

If all tests and reports go well, it will be promoted to master within the next few days.

**Comment by Cyan4973** [comment]
Merged to master
