### ISSUE TITLE
zstd 0.7.4 uncompresses random buffer without error

### ISSUE THREAD

**Issue by hashbackup** [Cyan4973/zstd#251]
zstd is in the next release of HashBackup.  HB uses the simple raw non-framed compress and decompress procedures since it already has a sha1 hash for every block.  The Python library is: https://github.com/sergey-dryabzhinsky/python-zstd/releases, version 0.4.7.  I downloaded and diff'd version 0.6.1, the differences are very minor, and I don't think it affects this issue.

The Python library compresses a block and includes a short header with the original uncompressed data length.  The decompress part looks like this (I added comments):
```
    header_size = sizeof(dest_size);   -- 4 bytes

    memcpy(&dest_size, source, header_size);  -- copy orig source size to dest_size
    result = PyBytes_FromStringAndSize(NULL, dest_size);  -- create empty Python string this big

    source += header_size;  -- skip over size header

    if (result != NULL && dest_size > 0) {  -- if Python alloc worked and is > 0
        char *dest = PyBytes_AS_STRING(result);  -- get C string pointer

        cSize = ZSTD_decompress(dest, dest_size, source, source_size - header_size);
        printf("dest_size=%d, cSize=%d\n", dest_size, cSize);    -- I added this
        if (ZSTD_isError(cSize))
            PyErr_Format(ZstdError, "Decompression error: %s", ZSTD_getErrorName(cSize));
    }

    return result;
```
I have a 1K block of random data that I mistakenly ran through the decompressor.  I know I'm running with "the safety off", and that's okay - just reporting this in case there is something else going on.

When I decompressed this random buffer, there was no decompression error signaled, but the string returned to Python was over 1GB.  Here's a test program:
```
[jim@mb hbrel]$ cat x.py
import os
import zstd

fd = os.open('badzstd', os.O_RDONLY)
data = os.read(fd, 1000000)
print 'len(data) is', len(data)
uncompdata = zstd.decompress(data)
print 'len(uncompdata) is', len(uncompdata)

[jim@mb hbrel]$ py x.py
len(data) is 1024
dest_size=1465475255, cSize=-11
len(uncompdata) is 1465475255

```
One easy fix is to change the Python interface module so that it checks that the returned size is exactly equal to the original source size; I'll suggest it to the author.  

But it seems there was also a memory overwrite in ZSTD_decompress that corrupted the Python string length.  So my questions are:

- should ZSTD_isError have signaled an error for a return value of -11?
- if simple decompress is used with bad data, is a memory overwrite supposed to be possible?

ZSTD_decompress is a low-level interface, so it's fine if it causes a memory overwrite.  It's my bug, not a zstd bug, and doesn't make sense to me to lower the compression speed to check for things like this.  But I figured I would attach the bogus buffer if it's not intended to work this way.
[badzstd.zip](https://github.com/Cyan4973/zstd/files/369689/badzstd.zip)

**Comment by hashbackup** [comment]
I did a little more digging on this, and maybe zstd has nothing to do with it.

An od of the bad block shows this:

[jim@mb hbrel]$ od -i badzstd |head
0000000        1465475255      1116800388     -1408337507     -1176177548

So that's where the goofy length is coming from.  As near as I can tell, the Python interface believes the expanded buffer will be 1.4GB, allocates a string that big, passes it to ZSTD_decompress, and it returns -11, which I'm guessing is an error.  But, the Python interface module is still returning the string as result, even if ZSTD_IsError returns true.  I think when an error occurs, the Python interface has to free the thing in result and return null to indicate an error.

**Comment by hashbackup** [comment]
Just a follow-up: I opened an issue on the Python zstd interface site and submitted a diff to fix it.  Here are some simple tests that show how it works after the changes:
```
>>> import zstd
>>> zstd.decompress('12')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: input too short
>>> zstd.decompress('1234')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
zstd.Error: Decompression error: Src size incorrect
>>> zstd.decompress('11111123456789')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
zstd.Error: Decompression error: Corrupted block detected
>>> 
```

**Comment by Cyan4973** [comment]
Excellent investigation @hashbackup !

I guess that's the reason why Serguey [recently updated its python wrapper](https://github.com/sergey-dryabzhinsky/python-zstd/releases/tag/v0.6.1.1).
