### ISSUE TITLE
`zstd --test` returns zero on non-archives.

### ISSUE THREAD

**Issue by amnilsson** [Cyan4973/zstd#261]
Lets assume a random file, of a non-zero length, with the .zst filename extension. When trying to decompress it (using `-d`), an error message is given (as expected): `zstd: <file>: not in zstd format`

But, when calling `zstd --test <file>`, zstd returns a zero value, and no warning or error is given, indicating that the test was successful.

Thus a sufficiently corrupted zstd-file could theoretically pass the test, even thought it can't be decompressed. It would also be beneficial when writing scripts, if files not in zstd-format returned a non-zero value.

**Comment by Cyan4973** [comment]
Thanks for report @amnilsson .

Indeed, it should exit with a non-zero return code.
I'm surprised, this use case is supposed to be checked by test script.
Will look into it ....

**Comment by Cyan4973** [comment]
I'm able to reproduce the bug with `v0.7.4`, but not with latest `dev` branch.

I guess it was solved by one intermediate patch, although I'm unsure which one.

I'm nonetheless surprised such a bug could get through.
It was supposed to be tested : 
https://github.com/Cyan4973/zstd/blob/master/programs/playTests.sh#L208

I suspect that's because `*` expanded to a list containing a directory, which properly failed,
thus masking the other cases which did not.
Hence it means the test must be strengthened a bit ...

**Comment by amnilsson** [comment]
Happy to help! :-)

I tried the dev08 branch. Non-archive files are now recognized, and the return value now seems to correspond to the number of input files containing errors, and is thus always non-zero in case of error(s). Thank you!

Regarding files of zero length. These pass the test, and can be "decompressed" (if they have a .zst filename extension). Is this really correct?

The test of a zero length file should IMHO fail. This would help detect errors where the file content has disappeared (like failed or erroneous I/O redirection in the shell).

Are files of zero length technically of the zstd format? IMHO they should not be, and decompression attempts should result in error, or at least a warning, to help detect data corruption. Is there a use case of zero length .zst files that I'm missing?

**Comment by Cyan4973** [comment]
You are totally right @amnilsson , `0` sized file should not pass the test.
I'll look into it, and add this test to the CI suite.

**Comment by Cyan4973** [comment]
0-sized files are reported as bad files in latest update of dev08 branch.
Tests updated to include this use case.

**Comment by amnilsson** [comment]
Nice! Thank you!
