### ISSUE TITLE
Are MEM_STATIC functions supposed to be inlined?

### ISSUE THREAD

**Issue by ebiggers** [Cyan4973/zstd#263]
I noticed this code in `mem.h`:

```
#if defined(__GNUC__)
#  define MEM_STATIC static __attribute__((unused))
#elif defined (__cplusplus) || (defined (__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L) /* C99 */)
#  define MEM_STATIC static inline
#elif defined(_MSC_VER)
#  define MEM_STATIC static __inline
#else
#  define MEM_STATIC static  /* this version may generate warnings for unused static functions; disable the relevant warning */
#endif
```

It looks like the functions are declared `inline` for other compilers but not for GCC and clang --- why is that?

I also noticed, in particular, that `BIT_reloadDStream()` was not being inlined when I compiled Zstandard with GCC.  Declaring it `inline` made decompression about 6% faster.

**Comment by Cyan4973** [comment]
:+1: 

Very good point !

Yes, they are supposed to be inlined.
In general, they are, because they are so short, most (if not all) compilers will automatically inline them.

But when `MEM_STATIC` is used outside of `mem.h`, that's less clear. 
`BIT_reloadDStream()` is probably no longer small enough to guarantee being inlined, which is detrimental to its performance.

You are totally right, this must be improved.

**Comment by Cyan4973** [comment]
I quickly changed
`#  define MEM_STATIC static __attribute__((unused))`
into
`#  define MEM_STATIC static __inline __attribute__((unused))`

and made some comparisons on `clang`.

It resulted in a sizable 5% speed improvement on the _compression_ side, but unexpectedly, nothing changed on the _decompression_ side...

**Comment by ebiggers** [comment]
Well, it is up to the compiler.  The specific case I tested where `BIT_reloadDStream()` wasn't being inlined was compiling for x86_64 with `-O2` with GCC 6.1.1.  I think that functions like this should be explicitly marked inline.

**Comment by Cyan4973** [comment]
You are right, with `gcc -O2`, the difference can be _very_ large. I measure up to 20% improvements ... :open_mouth:

**Comment by ebiggers** [comment]
I confirmed that `BIT_reloadDStream()` is now being inlined and the performance with `gcc -O2` is now faster.  So I'm closing this issue.

Before:
```
Method                        Csize (bytes)  Ctime (ms) Dtime(ms)
----------------------------- -------------  ---------- ---------
ZSTD -7                       61973092       5421       395       
ZSTD -6                       62978822       3850       402       
ZSTD -5                       65003263       2656       416       
ZSTD -1                       73666433       952        369       
```

After:
```
Method                        Csize (bytes)  Ctime (ms) Dtime(ms)
----------------------------- -------------  ---------- ---------
ZSTD -7                       61973092       5400       381       
ZSTD -6                       62978822       3849       380       
ZSTD -5                       65003263       2597       392       
ZSTD -1                       73666433       915        345       
```
