### ISSUE TITLE
potential type mismatch on i386  and 32-bit arch

### ISSUE THREAD

**Issue by jrmarino** [Cyan4973/zstd#269]
Hi Yann,
I noticed something that could be a potential (albeit rare in practice) issue.

The prototype for ZSTD_getDecompressedSize is
```
unsigned long long ZSTD_getDecompressedSize(const void* src, size_t srcSize);
```
unsigned long long is always a 64-bit integer IIUC.

The output of this function feeds into dstCapacity argument of ZSTD_decompress typically:
```
size_t ZSTD_decompress( void* dst, size_t dstCapacity,
                              const void* src, size_t compressedSize);
```

The issue is that while size_t is a 64-bit unsigned integer on x86_64, it's only a 32-bit unsigned integer on i386.  So presumably this effectively limits decompression to 4Gb on 32-bit architectures, after which ZSTD_decompress will likely fail I think.  Is my analysis correct?

**Comment by jrmarino** [comment]
(I understand a normal i386 machine has less than 4Gb memory)

**Comment by jrmarino** [comment]
Okay, feel free to close the issue.
I'm working on bindings for the Ada language and Ada caught this.  I'll submit a PR to update your documentation when it's done.

**Comment by Cyan4973** [comment]
Comments clarified within v0.8.0.
Please let me know if this is not enough.

**Comment by jrmarino** [comment]
Thanks! I think the clarifications are sufficient.
