### ISSUE TITLE
dictionary compression example: missing ZSTD_freeCDict ?

### ISSUE THREAD

**Issue by jrmarino** [Cyan4973/zstd#273]
I'm looking over the dictionary compression example.  I see the dictionary created (https://github.com/Cyan4973/zstd/blob/master/examples/dictionary_compression.c#L152) but I don't see it released with ZSTD_freeCDict. 

I know the program ends right after it should be released, but I was wondering if ZSTD_freeCDict should be added for A) to demonstrate it B) to demonstrate good practices?

**Comment by Cyan4973** [comment]
Yes you are totally right.
I tend to be less strict about that when in `main()`, since by definition the program ends there, and therefore must release memory.
But as you say, it's better to do it anyway, if only for A) and B)

**Comment by Cyan4973** [comment]
Ah, yes there is a small issue,
the initial intention was to create dictionaries as `const ZSTD_CDict*`,
but this cause later issue with `free()`, 
because `free()` is unfortunately incompatible with `const type*`.
So the dictionary must be created as `ZSTD_CDict*` instead.

**Comment by jrmarino** [comment]
solved in dev branch, closing.
