### ISSUE TITLE
ZSTD_ERROR_GENERIC failure on sample data

### ISSUE THREAD

**Issue by mwiebe** [Cyan4973/zstd#28]
I've run into a bit of data which fails to compress. The failure case is a binary file in the following gist:

https://gist.github.com/mwiebe/c54c790288b8e16a7970

```
C:\Dev>dir bad.bin
 Volume in drive C is Windows
 Volume Serial Number is DA14-224A
 
 Directory of C:\Dev
 
2015-03-23  02:17 PM             2,469 bad.bin
               1 File(s)          2,469 bytes
               0 Dir(s)  273,715,097,600 bytes free
 
C:\Dev>"C:\Dev\zstd\visual\2012\x64\Release\zstd.exe" bad.bin out.bin
Error 24 : Compression error : ZSTD_ERROR_GENERIC
```

**Comment by Cyan4973** [comment]
Thanks for notifying. I'll look into it.

**Comment by Cyan4973** [comment]
Latest version into "dev" branch is expected to solve this issue

**Comment by mwiebe** [comment]
Thanks, zstd is great work, can't wait for it to get to a stable state!

**Comment by Cyan4973** [comment]
You're welcomed Mark.
I'll issue a statement when zstd reaches stable status.
