### ISSUE TITLE
Build with debug symbols?

### ISSUE THREAD

**Issue by david-y-lam** [Cyan4973/zstd#309]
Does this exist?

**Comment by nabijaczleweli** [comment]
Yes, you pass `-g` (optionally with `-Og`) to a C compiler when building `zstd`

**Comment by david-y-lam** [comment]
@nabijaczleweli, thanks. it seems like the Makefile commands don't pass in `-g` anywhere, so I should rephrase the question - should we do it?

**Comment by nabijaczleweli** [comment]
If you want `zstd` to have debug symbols then compile it with `-g`, any and all Makefiles are irrelevant

**Comment by inikep** [comment]
@david-y-lam try `make CFLAGS=-g`
It should replace `-O3` with `-g`.

**Comment by david-y-lam** [comment]
thanks @inikep
