### ISSUE TITLE
Segfault during decompression

### ISSUE THREAD

**Issue by IIoTeP9HuY** [Cyan4973/zstd#34]
Hello! Thanks for a great library!
I've recently encountered problem while decoding data generated by this script:

```(python)
#!/usr/bin/env python

import sys

n = int(sys.argv[1])

for i in range(0, n):
    sys.stdout.write(chr(i + ord('a')) * (2**i))
```

When I run:
```(bash)
  ./generate.py 20 > input 
  ./zstd -f input compressed  # Compressed 1048575 bytes into 235 bytes ==> 0.02%
  ./zstd -f -d compressed decompressed # Segmentation fault
```
I get segmentation fault.

If I replace 20 with 19 I get:
```(bash)
  ./generate.py 19 > input 
  ./zstd -f input compressed  # Compressed 524287 bytes into 159 bytes ==> 0.03%
  ./zstd -f -d compressed decompressed # Decoded 262144 bytes
```
Which is weird because decompressed input size doesn't match original input size.

I faced this situation on OSX 10.10 and on Ubuntu 12.04 with both Clang and GCC 4.9

**Comment by Cyan4973** [comment]
Thanks for pointing that out.
I'll definitely look into it.

**Comment by maxim-babenko** [comment]
Hi! Any update on this issue? We're suffering from it too.

**Comment by Cyan4973** [comment]
FSE is currently receiving an overhaul. Zstd is next in the list. Expect an update correcting this issue this Summer.

**Comment by Cyan4973** [comment]
I could reproduce the problem. I'll look into it for a correction.

**Comment by Cyan4973** [comment]
Got it.
It's a special corner case that the current decoder cannot detect properly.
Knowing this, it's up to the encoder to present such data into an easier presentation.
On the encoding side, the change is not trivial, but certainly possible.
Let's try that ...

**Comment by Cyan4973** [comment]
Latest version available in "dev" branch seems to fix this issue.

**Comment by Cyan4973** [comment]
pushed to master
