### ISSUE TITLE
ZSTD_decompressContinue requires previous decompressed buffer

### ISSUE THREAD

**Issue by cielavenir** [Cyan4973/zstd#45]
ZSTD_decompressContinue() requires previous decompressed buffer, which is incompatible with zstd_static.h document.

PS. fileio.c is GPL again... Do you plan to consider? Also, FIO_decompressFilename()'s **wNbBlocks** is a kind of magic number (because undocumented).

Note: You can use http://pastebin.com/XTTUSyiA as an example code.

**Comment by Cyan4973** [comment]
> ZSTD_decompressContinue requires previous decompressed buffer

Yes, this is correct.
I will add some comments to make this condition clear.

As a general notice : note that API within `zstd_static.h` should be considered experimental, not yet ready for general usage, nor stable. Typically, I'm not yet satisfied by the block streaming interface, so the API itself and/or its properties may change in the future.

> fileio.c is GPL again
> wNbBlocks is a kind of magic number (because undocumented)

Correct.
`fileio.c` is not ready for usage beyond `ztsdcli`. It would need some serious shakeup to be considered "safe and stable" for integration into any 3rd-party program. The constant you underlined is one of the things to improve, and there are quite a lot more. For example, `lz4io.c` not even thread-safe.

When I feel it's good enough to be used outside of `ztsdcli` context, it will be considered for BSD license.

Regards

**Comment by Cyan4973** [comment]
1) There is a new streaming API, `zstd_buffered`, which is highly recommended for streaming applications. It takes care of everything, and therefore eliminates any requirement regarding buffer management from the caller.

2) The bufferless streaming API still exists (`zstd_static.h`) and has been improved and clarified. It provides the core functionalities for `zstd_buffered`. Should you prefer to manage directly your own buffers, it's the way to go.

Please let me know if streaming API is still an issue for you.

**Comment by cielavenir** [comment]
It looks fine (at least currently). http://pastebin.com/2WH0iERW
