### ISSUE TITLE
gcc pedantically complains about that comma... :)

### ISSUE THREAD

**Issue by biller23** [Cyan4973/zstd#6]
zstd_static.h:74:38: warning: comma at end of enumerator list [-Wpedantic]

**Comment by Cyan4973** [comment]
Thanks for notification.
Unfortunately, this warning is a bit difficult to fix, since it would require to change the macro generating enums.

Probably adding a useless element at the end of the list would work. But I don't think it's cleaner than the trailing comma.

**Comment by biller23** [comment]
Got it. Thanks anyway. I will close this little issue.
