### ISSUE TITLE
Visual Studio 2012 Release broken

### ISSUE THREAD

**Issue by mailagentrus** [Cyan4973/zstd#60]
Visual Studio 2012 Release mode - decompress data (which generated in HC mode) is broken again... Debug - is OK :)
Seems like a bug as in 0.2 version...

**Comment by mailagentrus** [comment]
Running "fullbench" in release mode (MSVC 2012) enters in infinite loop in decompress mode too...

**Comment by Cyan4973** [comment]
Thanks for notification,
:( something went wrong during branch merge...

**Comment by mailagentrus** [comment]
Use huff0 from issue #52 :))

**Comment by Cyan4973** [comment]
This should be fixed into "dev" branch now

**Comment by Cyan4973** [comment]
Fix released : https://github.com/Cyan4973/zstd/releases/tag/zstd-0.3.2
