### ISSUE TITLE
HC_compress issues

### ISSUE THREAD

**Issue by luben** [Cyan4973/zstd#62]
Hi,

I am running into some issues with decompressing some of the results of ZSTD_HC_compress. I am using the very simple test case pasted below.

Trying to decompress the result of compressing 0 bytes buffer with level > 1 I am getting "ZSTD_error_corruption_detected" and with larger sizes buffer I am getting "ZSTD_error_srcSize_wrong". When I pass a certain threshold (15 in this case but it depends on the payload) everything starts to works correctly.

```c
#include <stdio.h>
#include <stdlib.h>
#include <zstd.h>
#include <zstdhc.h>

int main(int argc, char **argv ) {
    char raw[20] = {1,1,1,1,1, 1,1,1,1,1, 1,1,1,1,1, 1,1,1,1,1};
    char compressed[50];
    char decompressed[50];
    size_t ccode, dcode;
    size_t size = 2;
    int level = 2;

    ccode = ZSTD_HC_compress(compressed, 50, raw, size, level);
    printf("Compression code %i\n", ccode);
    if (ZSTD_isError(ccode)) {
        printf("Compression error %s\n", ZSTD_getErrorName(ccode));
    }

    dcode = ZSTD_decompress(decompressed, 50, compressed, ccode);
    printf("Decompression code %i\n", dcode);
    if (ZSTD_isError(dcode)) {
        printf("Decompression error %s\n", ZSTD_getErrorName(dcode));
    }
    return 0;
}
```

**Comment by luben** [comment]
Ops, looks already fixed in dev branch.

**Comment by luben** [comment]
ops again... it's not fixed, I have tested with compression_level=1

**Comment by Cyan4973** [comment]
OK,
trying to understand the issue,
what is the size you are testing ? Is it the size of data compress ?

**Comment by luben** [comment]
yes, with small sized of data compressed with the HC_compress is gives errors when trying to decompress the result. In the above code if you vary the "size" it will fail decompressing it until size reaches 16.

**Comment by Cyan4973** [comment]
OK, thanks.
I'll look into it.

**Comment by Cyan4973** [comment]
Thanks for report.

Issue should be fixed within latest "dev" branch update.
There are also some changes tests within fuzzer to ensure this condition is properly tested and verified at each update.

Regards

**Comment by luben** [comment]
Confirming that it is fixed. Thanks a lot
