### ISSUE TITLE
Cmake support

### ISSUE THREAD

**Issue by mailagentrus** [Cyan4973/zstd#66]
I can prepare and push CMakeLists.txt file for generating solution or make file on different platforms. I don't know if this feature will be useful or not?

**Comment by Cyan4973** [comment]
That's a good idea.

cmake usage is typically a minority, but a non-negligible one. So it will be useful.

**Comment by Cyan4973** [comment]
It is still planned to create a `cmake` build file ?

**Comment by Cyan4973** [comment]
I'll close it for now. Just reopen or create a PR in case of new elements.
