### ISSUE TITLE
+ Brotili to comparison?

### ISSUE THREAD

**Issue by tomByrer** [Cyan4973/zstd#68]
[Cloudflare is seeking better compression](https://blog.cloudflare.com/results-experimenting-brotli/}, so I was wondering how this would compare to another actively developed compressor [brotili](https://github.com/google/brotli)?

**Comment by Cyan4973** [comment]
In general, expect better speed from Zstandard, especially on the decompression speed side.

I haven't yet investigated small data blocks, which seems the core concern of CloudFlare tests.
I have to spend some more time on it before going for a comparison.
The current settings would probably not fare well in such scenario.

But it's just a matter of time ...

**Comment by tomByrer** [comment]
Yes, I was getting the feeling you are focused on larger files.
Perhaps [3d meshes](https://github.com/google/brotli/issues/165) would be a better use-case for you now?

**Comment by Cyan4973** [comment]
Indeed, it's an interesting use case (thanks for the link).
It will require some dedicated optimizations.
Let's keep that objective for a later stage ...

**Comment by tomByrer** [comment]
Welcome!

You can close this, or keep open as a reminder for yourself.  (I'm using Issues just to chat :) )

**Comment by Cyan4973** [comment]
Let's re-open it when we get ready for that
