### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by kdmurray91** [Cyan4973/zstd#71]
Hi Yann,

I'm just posting this as a courtesy message to say that I intend to package the Zstd library for [Debian](https://www.debian.org). A quick question for you, is the preferred name "zstd", or "zstandard"?

I'll post back with progress as it occurs.

Cheers,
Kevin

**Comment by Cyan4973** [comment]
Thanks for the heads up Kevin.

`zstd` is more a shortcut for programmatic environments.

For normal users, I believe __Zstandard__ is more understandable, and therefore should be preferred.

Also : note that current compressed format is not yet final, so it should be mentioned somewhere, like "experimental" or something like that.

Regards

**Comment by jforberg** [comment]
FYI I'm the current maintainer of the Arch (AUR) package, which I have called zstd.

**Comment by Cyan4973** [comment]
Have you finally selected a name @kdmurray91 ?
Should this issue remain opened ?

**Comment by kdmurray91** [comment]
Hi Yann,

Sorry for not posting back. I have decided on `libzstd` as the package name.  I'll also note in the Readme.debian that this is not a finalised format.

**Comment by kdmurray91** [comment]
FYI, the Intent To Package bug is at https://bugs.debian.org/806767 for anyone interested.

**Comment by kdmurray91** [comment]
Just to let you know, the debian package has been accepted into unstable. This means that it should make it into the next debian release.

Cheers,
Kevin

**Comment by Cyan4973** [comment]
Great news Kevin !

**Comment by Cyan4973** [comment]
Hi @kdmurray91 , 
are you still active on this topic ?
We are looking for some help to make Ubuntu update its package in its LTS edition.
