### ISSUE TITLE
Unexpected error for huge data

### ISSUE THREAD

**Issue by t-mat** [Cyan4973/zstd#8]
I've got unexpected error for huge (>4GiB ?) data which generated by xorshift. Here is a test case : https://gist.github.com/t-mat/a7e93d4767b991e191ea
It generates same error both on Ubuntu 14.04 (x64) / gcc 4.8.2 and Windows 7 SP1 (x64) / MSVC++2013.

```
source data       : 4295000064 bytes
zstd compressed   : 1350556646 bytes
zstd decompressed : 4295000064 bytes
Data error : offset @0x100003c41
```

**Comment by Cyan4973** [comment]
Thanks Takayuki

I suspect that, in my hastiness to release zStd, I forgot to re-enable a match offset limit, which is useless in most circumstances, but should prove useful in such a case.

I'll look into it.

**Comment by Cyan4973** [comment]
There's a new version available in the "dev" branch which is supposed to fix this issue.
I can't test it directly, since my system would not allow me to allocated that much memory.
Would you mind having a look ?

Regards

**Comment by t-mat** [comment]
Confirmed. New logic works fine both Ubuntu and Windows.

But new code has another problem.

Using `defined(_INCLUDED_IMM)` for AVX2 detection is really problematic. It detects just a existence of the header. But it does not indicate compiler's code generation capability and target architecture. For example, currently we can't genarete generic x86-64 binary for non-AVX2 environment.

Please remove `defined(_INCLUDED_IMM)` from AVX2 detection.

**Comment by Cyan4973** [comment]
OK.
Is __AVX2__ macro detection enough for this, on both Unix & Windows ?

**Comment by t-mat** [comment]
Yes. Recent gcc, clang, [icc](https://software.intel.com/en-us/node/514528) and [MSVC](https://msdn.microsoft.com/en-us/library/jj620901.aspx) has predefined `__AVX2__` macro for AVX2 target.

```
$ gcc -march=core-avx-i -dM -E -x c /dev/null | grep "AVX"
#define __AVX__ 1

$ gcc -march=core-avx2 -dM -E -x c /dev/null | grep "AVX"
#define __AVX__ 1
#define __AVX2__ 1

$ clang -march=core-avx-i -dM -E -x c /dev/null | grep "AVX"
#define __AVX__ 1

$ clang -march=core-avx2 -dM -E -x c /dev/null | grep "AVX"
#define __AVX2__ 1
#define __AVX__ 1
```

I'm not sure we should support older compiler or not, but optional configure macro (eg. `ZSTD_ENABLE_AVX2`) would be nice for some people.

**Comment by Cyan4973** [comment]
Excellent suggestion. Thanks Takayuki.
