### ISSUE TITLE
Zstd-0.4.0 compiled without legacy support

### ISSUE THREAD

**Issue by luben** [Cyan4973/zstd#80]
When I try to decompress a freshly compressed file, it is correctly decompressed but at the end I get:
Error 35 : Read error

**Comment by luben** [comment]
I am not sure it this is the right fix:

```diff
diff --git a/programs/fileio.c b/programs/fileio.c
index e84d633..9aa5bf2 100644
--- a/programs/fileio.c
+++ b/programs/fileio.c
@@ -384,7 +384,6 @@ unsigned long long FIO_decompressFilename(const char* output_filename, const cha
     {
         toRead = 0;
 
-#if defined(ZSTD_LEGACY_SUPPORT) && (ZSTD_LEGACY_SUPPORT==1)
         {
             size_t sizeCheck;
             /* check magic number -> version */
@@ -392,13 +391,14 @@ unsigned long long FIO_decompressFilename(const char* output_filename, const cha
             sizeCheck = fread(inBuff, (size_t)1, toRead, finput);
             if (sizeCheck==0) break;   /* no more input */
             if (sizeCheck != toRead) EXM_THROW(31, "Read error : cannot read header");
+#if defined(ZSTD_LEGACY_SUPPORT) && (ZSTD_LEGACY_SUPPORT==1)
             if (ZSTD_isLegacy(MEM_readLE32(inBuff)))
             {
                 filesize += FIO_decompressLegacyFrame(foutput, finput, MEM_readLE32(inBuff));
                 continue;
             }
-        }
 #endif   /* ZSTD_LEGACY_SUPPORT */
+        }
 
         filesize += FIO_decompressFrame(foutput, finput, inBuff, inBuffSize, toRead, outBuff, outBuffSize, dctx);
     }
```

**Comment by Cyan4973** [comment]
Thanks for notification @luben .

Indeed, this is a path I haven't thoroughly tested.
I should add relevant tests in CI suite, to make sure it's correctly tracked.

Your patch looks good to me. I believe it's the correct fix.

**Comment by Cyan4973** [comment]
Hopefully fixed in latest "dev" branch update

**Comment by Cyan4973** [comment]
Btw, I've got a question regarding no-legacy builds.

Currently, building with no-legacy is triggered using `ZSTD_LEGACY=disable` .

In the source code, it is done with `#define ZSTD_LEGACY_SUPPORT 0`

Thus, they are a little bit different.
I'm wondering if it would be better to follow a single convention, such as `ZSTD_LEGACY_SUPPORT=0` for both.

**Comment by luben** [comment]
Yes, makes sense. I was looking in the Makefiles for find what I have to pass in order to disable it after first trying with ZSTD_LEGACY_SUPPORT=0

**Comment by Cyan4973** [comment]
Parameter changed to ZSTD_LEGACY_SUPPORT=0 within latest dev branch.
