### ISSUE TITLE
VS2008 Compilation Issue: Cannot open include file: 'immintrin.h'

### ISSUE THREAD

**Issue by russellwinstead** [Cyan4973/zstd#9]
I was looking at making simple python wrappers for the zstd library, and I ran into the following issue when compling on Windows using VS2005:

lib\zstd.c(69) :fatal error C1083: Cannot open include file: 'immintrin.h': No such file or directory

It appears to come from [this line](https://github.com/Cyan4973/zstd/blob/00f9507d26ededd25f8fc023c9f58113a609a27b/lib/zstd.c#L69).

**Comment by Cyan4973** [comment]
Yes, indeed.
immintrin.h is about AXV2 extension.
So it's probably not available on VS2005.

The manual solution is to comment this line : the associated code will be removed from compilation.

What I'm lacking currently is a way to achieve this conditional #include automatically.

**Comment by Cyan4973** [comment]
There is a tentative fix for your configuration within the "dev" branch of zstd : 
https://github.com/Cyan4973/zstd/tree/dev

For your testings

**Comment by russellwinstead** [comment]
I think the logic on the conditional is reversed.  After changing `_MSC_VER<=1400` to `_MSC_VER>1400` everything seemed to work out fine.

**Comment by russellwinstead** [comment]
Sorry, I said 2005 but I meant 2008.  After changing `_MSC_VER<=1400` to `_MSC_VER<=1500` everything turned out ok.

**Comment by Cyan4973** [comment]
OK, "dev" branch updated
